/**
 * Project Euler: Problem 2: Even Fibonacci Numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be:
 *
 * 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued
 * terms.
 */

#include <assert.h>

int fiboEvenSum(int n) {
  int sum = 0;
  int prev = 1;
  int cur = 1;
  while (cur <= n) {
    int tmp = cur;
    cur = cur + prev;
    prev = tmp;

    if (cur % 2 == 0) {
      sum += cur;
    }
  }
  return sum;
}

int main(void) {
  assert(fiboEvenSum(10) == 10);
  assert(fiboEvenSum(34) == 44);
  assert(fiboEvenSum(60) == 44);
  assert(fiboEvenSum(1000) == 798);
  assert(fiboEvenSum(100000) == 60696);
  assert(fiboEvenSum(4000000) == 4613732);
}
